language: python
python:
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source=mutpy -m unittest discover -s mutpy/test
after_success:
  coveralls
